version: "3.8"
services:
  database:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_COLLATION: ${POSTGRES_COLLATION}
    volumes:
      - ./database/pgdata:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  backend:
    container_name: backend-container
    env_file:
      - ./.env
    environment:
      POSTGRES_SERVER: database
    build:
      context: ./backend
    volumes:
      - ./backend/node_modules:/home/node/backend/node_modules
    ports:
      - "8081:8080"
    links:
      - database
    depends_on:
      - database
  nginx-react:
    container_name: nginx-react-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx/:/etc/nginx
      - ./nginx/log:/var/log/nginx
    ports:
      - "80:80"
      # - "443:443"
